skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
m0 = "BseL5WXo2AZY5kqqhLbsmnH7FnXFFiKfMiNDAcojjmEJ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
